#!/usr/bin/env python3
# scrapes new senators names and images.
import os
import json
import logging
from datetime import datetime
# Use requests_html when JS is required on website
# https://requests.readthedocs.io/projects/requests-html/en/latest/
from requests_html import HTMLSession

session = HTMLSession()

# Change based off of which site being scraped
BASE_URL = 'https://en.wikipedia.org/w/index.php?title=List_of_current_United_States_senators'
# TODO: dynamically generate state ids
#  BASE_IMG_PATH = f'https://www.citystats.xyz/images/states/{STATE_ID}/senator/'

# TODO: dynamically generate state ids
PATH_ID = f'{STATE_ID}'
IMG_PATH = f'./new_senate_members/img/{PATH_ID}/'

CURR_DATE = datetime.now().strftime('%d_%m_%Y')
LOG_FILENAME = f'log_{CURR_DATE}.txt'
os.makedirs(os.path.dirname(IMG_PATH), exist_ok=True)

log_format = '%(asctime)s - %(levelname)s - %(message)s'
logging.basicConfig(filename=LOG_FILENAME,
                    level=logging.INFO,
                    format=log_format)
console_handler = logging.StreamHandler()
console_handler.setFormatter(logging.Formatter(log_format))
logging.getLogger().addHandler(console_handler)

#  def download_images(img_arr):
#  for i, img_url in enumerate(img_arr):
#  # uri string conversion (i.e. %20 spaces %3F question marks, etc.)
#  if '.png' in img_url:
#  file_name = f'./new_council_members/img/{PATH_ID}/{PATH_ID}_{i}.png'
#  else:
#  file_name = f'./new_council_members/img/{PATH_ID}/{PATH_ID}_{i}.jpg'
#  # 403 passed without user agent string
#  img_data = requests.get(
#  img_url,
#  stream=True,
#  headers={
#  'User-agent': 'Mozilla/5.0'
#  },
#  ).content
#  file = open(f'{file_name}', 'wb')
#  file.write(img_data)
#  logging.info(
#  f'Downloaded image for city_id: {CITY_ID}, {i + 1} of {len(img_arr)}'
#  )


def parse_json(results):
    json_arr = []
    for result in results:
        data = {}
        # TODO: dynamically generate state ids
        #  data['state_id'] = STATE_ID
        data['senator'] = result
        json_arr.append(data)
    for i, data in enumerate(json_arr):
        data['img_url'] = f'{BASE_IMG_PATH}/{i}'
    with open(f'./new_senate_members/json/{PATH_ID}.json', 'w') as writeJSON:
        json.dump(json_arr, writeJSON, ensure_ascii=False)


#  def grab_member_img():
#  try:
#  r = session.get(CITY_COUNCIL_URL)
#  # r.html actually works, lsp doesn't like it for some reason...
#  data = []
#  results = r.html.find('.clearfix')
#  for result in results:
#  images = result.find('img')
#  for image in images:
#  if 'src' in image.attrs:
#  if image.attrs['src'] not in data:
#  data.append(image.attrs['src'])
#  return data
#  except Exception as e:
#  logging.error(f'Error at city_id: {CITY_ID} during scraping: {str(e)}')
#  return False


def scrape_data():
    try:
        r = session.get(BASE_URL)
        # r.html actually works, lsp doesn't like it for some reason...
        data = []
        results = r.html.find('.sidenav_expanded')
        for result in results:
            a_tags = result.find('a')
            for a_tag in a_tags:
                if 'href' in a_tag.attrs and 'city-council-members' in a_tag.attrs[
                        'href']:
                    if len(a_tag.text) and a_tag.text not in data:
                        data.append(a_tag.text)
        del data[0]
        for i, d in enumerate(data):
            if 'President' in d:
                data[i] = d.split('President ')[1]
            elif 'Majority' in d or 'Minority' in d:
                data[i] = d.split(', ')[1]
            else:
                data[i] = d.split(', ')[0]
        return data
    except Exception as e:
        logging.error(
            # TODO: dynamically generate state ids
            f'Error at city_id: {STATE_ID} during scraping: {str(e)}')
        return False


if __name__ == "__main__":
    senator_names = scrape_data()
    #  if results:
    #  parse_json(results)
    #  member_img_urls = grab_member_img()
    #  img_urls = prepend_mayor_img_url_to(member_img_urls)
    #  download_images(img_urls)
