#!/usr/bin/env python3
# scrapes council member names and images.
import os
import json
import requests
import logging
from datetime import datetime
from bs4 import BeautifulSoup as BS

# Change based off of which site being scraped
CITY_ID = 15
BASE_URL = 'https://citycouncil.atlantaga.gov'
CITY_COUNCIL_URL = 'https://citycouncil.atlantaga.gov/council-members/'
MAYOR_URL = 'https://www.atlantaga.gov/government/mayor-s-office/meet-the-mayor'
BASE_IMG_PATH = f'https://www.citystats.xyz/images/cities/{CITY_ID}'

PATH_ID = f'0{CITY_ID}'
IMG_PATH = f'./new_council_members/img/{PATH_ID}/'

CURR_DATE = datetime.now().strftime('%d_%m_%Y')
LOG_FILENAME = f'log_{CURR_DATE}.txt'

os.makedirs(os.path.dirname(IMG_PATH), exist_ok=True)

log_format = '%(asctime)s - %(levelname)s - %(message)s'
logging.basicConfig(filename=LOG_FILENAME,
                    level=logging.INFO,
                    format=log_format)
console_handler = logging.StreamHandler()
console_handler.setFormatter(logging.Formatter(log_format))
logging.getLogger().addHandler(console_handler)


def download_images(img_arr):
    for i, img_url in enumerate(img_arr):
        file_name = f'./new_council_members/img/{PATH_ID}/{PATH_ID}_{i}.jpg'
        img_data = requests.get(img_url).content
        file = open(f'{file_name}', 'wb')
        file.write(img_data)
        logging.info(
            f'Downloaded image for city_id: {CITY_ID}, {i + 1} of {len(img_arr)}'
        )


def grab_img_urls(member_urls):
    img_arr = []

    for url in member_urls:
        try:
            html = requests.get(url).content
            soup = BS(html, 'lxml')
            image_tags = soup.findAll('div', {"class": "image_widget"})
            for img in image_tags:
                if len(img.findAll('img')):
                    sub_url = img.findAll('img')[0]['src']
                    if sub_url:
                        img_url = f"{BASE_URL}{sub_url}"
                        img_arr.append(img_url)
        except Exception as e:
            logging.error(
                f'Error at city_id: {CITY_ID} grabbing image URL: {str(e)}')
            pass
    return img_arr


def parse_json(results):
    json_arr = []
    for result in results:
        data = {}
        data['city_id'] = CITY_ID
        try:
            # council_member usually needs to be changed
            data['council_member'] = result
            json_arr.append(data)
        except Exception as e:
            logging.error(
                f'Error at city_id: {CITY_ID} parsing JSON: {str(e)}')
            pass
    for i, data in enumerate(json_arr):
        if i == 0:
            data['img_url'] = f'{BASE_IMG_PATH}/mayor'
        else:
            data['img_url'] = f'{BASE_IMG_PATH}/city_council/{i}'
    with open(f'./new_council_members/json/{PATH_ID}.json', 'w') as writeJSON:
        json.dump(json_arr, writeJSON, ensure_ascii=False)


def scrape_data():
    try:
        html = requests.get(CITY_COUNCIL_URL).content
        soup = BS(html, 'lxml')
        # results is usually what needs to get changed
        results = soup.findAll('h3')
        data = []
        for result in results:
            a_tag = result.findAll('a')
            if len(a_tag):
                data.append(a_tag[0].text)
        return data
    except Exception as e:
        logging.error(f'Error at city_id: {CITY_ID} during scraping: {str(e)}')
        return False


def append_mayor(members_arr):
    try:
        html = requests.get(MAYOR_URL).content
        soup = BS(html, 'lxml')
        # results is usually what needs to get changed
        results = soup.findAll('h1')[1].contents[0].split(' ')[1:3]
        results = ' '.join(results)
        members_arr.insert(0, results)
        return members_arr
    except Exception as e:
        logging.error(f'Error at city_id: {CITY_ID} during scraping: {str(e)}')
        return False


def grab_member_urls():
    html = requests.get(CITY_COUNCIL_URL).content
    soup = BS(html, 'lxml')
    # results is usually what needs to get changed
    results = soup.findAll('h3')
    member_urls = []
    for result in results:
        if len(result.findAll('a')):
            member_urls.append(result.findAll('a')[0]['href'])
    return member_urls


def append_mayor_img(img_arr):
    html = requests.get(MAYOR_URL).content
    soup = BS(html, 'lxml')
    # results is usually what needs to get changed
    results = soup.findAll('div', {"class": "content_area"})
    for result in results:
        mayor_img_url = result.findAll('img')[0]['src']
        img_arr.insert(0, mayor_img_url)
    return img_arr


if __name__ == "__main__":
    results = scrape_data()
    results = append_mayor(results)
    if results:
        parse_json(results)
        member_urls = grab_member_urls()
        img_arr = grab_img_urls(member_urls)
        full_img_arr = append_mayor_img(img_arr)
        download_images(full_img_arr)
