#!/usr/bin/env python3
# scrapes council member names and images.
import os
import json
import requests
import logging
from datetime import datetime
from bs4 import BeautifulSoup as BS

# Change based off of which site being scraped
CITY_ID = 20
CITY_COUNCIL_URL = 'https://en.wikipedia.org/wiki/Bakersfield_City_Council'

PATH_ID = f'0{CITY_ID}'

CURR_DATE = datetime.now().strftime('%d_%m_%Y')
LOG_FILENAME = f'log_{CURR_DATE}.txt'

log_format = '%(asctime)s - %(levelname)s - %(message)s'
logging.basicConfig(filename=LOG_FILENAME,
                    level=logging.INFO,
                    format=log_format)
console_handler = logging.StreamHandler()
console_handler.setFormatter(logging.Formatter(log_format))
logging.getLogger().addHandler(console_handler)


def parse_json(results):
    json_arr = []
    for result in results:
        data = {}
        data['city_id'] = CITY_ID
        # council_member usually needs to be changed
        data['council_member'] = result
        data['img_url'] = None
        json_arr.append(data)
    with open(f'./new_council_members/json/{PATH_ID}.json', 'w') as writeJSON:
        json.dump(json_arr, writeJSON, ensure_ascii=False)


def scrape_data():
    try:
        html = requests.get(CITY_COUNCIL_URL).content
        soup = BS(html, 'lxml')
        # results is usually what needs to get changed
        results = soup.findAll('table', {"class": "wikitable"})
        inter_arr = []
        for result in results:
            res = result.findAll('td')
            for r in res:
                if len(r.text.strip()):
                    inter_arr.append(r.text.strip())
        data = []
        data.append(inter_arr[1])
        for i, el in enumerate(inter_arr):
            if el.isdigit():
                data.append(inter_arr[i + 1])
        for i, d in enumerate(data):
            if '(' in d:
                d = d.split('(')[0].strip()
                data[i] = d
        return data
    except Exception as e:
        logging.error(f'Error at city_id: {CITY_ID} during scraping: {str(e)}')
        return False


if __name__ == "__main__":
    results = scrape_data()
    if results:
        parse_json(results)
        logging.info(f'No images scraped for city_id: {CITY_ID}')
