#!/usr/bin/env python3
# scrapes council member names and images.
from urllib.parse import unquote
import json
import logging
import requests
from datetime import datetime
# Use requests_html when JS is required on website
# https://requests.readthedocs.io/projects/requests-html/en/latest/
from requests_html import HTMLSession

session = HTMLSession()

from bs4 import BeautifulSoup as BS

# Change based off of which site being scraped
CITY_ID = 39
BASE_URL = 'https://www.cambridgema.gov'
CITY_COUNCIL_URL = 'https://www.cambridgema.gov/citydirectory?page=1&department={4469559C-2AE6-483F-A00E-8F15B9797D78}&resultsPerPage=-1'

PATH_ID = f'0{CITY_ID}'

CURR_DATE = datetime.now().strftime('%d_%m_%Y')
LOG_FILENAME = f'log_{CURR_DATE}.txt'

log_format = '%(asctime)s - %(levelname)s - %(message)s'
logging.basicConfig(filename=LOG_FILENAME,
                    level=logging.INFO,
                    format=log_format)
console_handler = logging.StreamHandler()
console_handler.setFormatter(logging.Formatter(log_format))
logging.getLogger().addHandler(console_handler)


def parse_json(results):
    json_arr = []
    for result in results:
        data = {}
        data['city_id'] = CITY_ID
        # council_member usually needs to be changed
        data['council_member'] = result
        data['img_url'] = None
        json_arr.append(data)
    with open(f'./new_council_members/json/{PATH_ID}.json', 'w') as writeJSON:
        json.dump(json_arr, writeJSON, ensure_ascii=False)


def scrape_data():
    try:
        r = session.get(CITY_COUNCIL_URL)
        # r.html actually works, lsp doesn't like it for some reason...
        data = []
        results = r.html.find('tr')
        for result in results:
            td = result.find('td')
            if len(td):
                if td[2].text == 'Mayor':
                    data.insert(0, td[0].text)
                elif td[2].text == 'Vice-Mayor':
                    data.insert(0, td[0].text)
                elif td[2].text == 'City Councillor':
                    data.append(td[0].text)
        # names are reversed, putting them in order...
        for i, d in enumerate(data):
            temp = d.split(',')
            temp.insert(0, temp[-1].strip())
            temp.pop()
            data[i] = ' '.join(temp)
        return data
    except Exception as e:
        logging.error(f'Error at city_id: {CITY_ID} during scraping: {str(e)}')
        return False


if __name__ == "__main__":
    results = scrape_data()
    if results:
        parse_json(results)
    logging.info(f'No images scraped for city_id: {CITY_ID}')
