#!/usr/bin/env python3
# scrapes council member names and images.
import json
import logging
from datetime import datetime
# Use requests_html when JS is required on website
# https://requests.readthedocs.io/projects/requests-html/en/latest/
from requests_html import HTMLSession

session = HTMLSession()

# Change based off of which site being scraped
CITY_ID = 50
BASE_URL = 'https://chattanooga.gov'
CITY_COUNCIL_URL = 'https://chattanooga.gov/city-council/council-members'
MAYOR_NAME_URL = 'https://en.wikipedia.org/wiki/Chattanooga,_Tennessee?useskin=vector'
BASE_IMG_PATH = f'https://www.citystats.xyz/images/cities/{CITY_ID}'

PATH_ID = f'0{CITY_ID}'

CURR_DATE = datetime.now().strftime('%d_%m_%Y')
LOG_FILENAME = f'log_{CURR_DATE}.txt'

log_format = '%(asctime)s - %(levelname)s - %(message)s'
logging.basicConfig(filename=LOG_FILENAME,
                    level=logging.INFO,
                    format=log_format)
console_handler = logging.StreamHandler()
console_handler.setFormatter(logging.Formatter(log_format))
logging.getLogger().addHandler(console_handler)


def parse_json(results):
    json_arr = []
    for result in results:
        data = {}
        data['city_id'] = CITY_ID
        # council_member usually needs to be changed
        data['council_member'] = result
        data['img_url'] = None
        json_arr.append(data)
    with open(f'./new_council_members/json/{PATH_ID}.json', 'w') as writeJSON:
        json.dump(json_arr, writeJSON, ensure_ascii=False)


def scrape_data():
    try:
        r = session.get(CITY_COUNCIL_URL)
        # r.html actually works, lsp doesn't like it for some reason...
        data = []
        results = r.html.find('.moduletable')
        li_items = []
        for result in results:
            res = result.find('ul.nav')
            if len(res):
                for r in res:
                    for li in r.find('li'):
                        li_items.append(li)
        for li in li_items:
            text = (li.find('a')[0].text)
            if 'District' in text:
                data.append(text.split(',')[0])
        return data
    except Exception as e:
        logging.error(f'Error at city_id: {CITY_ID} during scraping: {str(e)}')
        return False


def append_mayor(member_names):
    try:
        r = session.get(MAYOR_NAME_URL)
        # r.html actually works, lsp doesn't like it for some reason...
        data = []
        results = r.html.find('tr.mergedrow')
        for result in results:
            res = result.find('tr')
            for r in res:
                a_tag = r.find('a')
                if (len(a_tag)):
                    data.append(a_tag[0].text)
        member_names.insert(0, data[3])
        return member_names
    except Exception as e:
        logging.error(f'Error at city_id: {CITY_ID} during scraping: {str(e)}')
        return False


if __name__ == "__main__":
    members_names = scrape_data()
    results = append_mayor(members_names)
    if results:
        parse_json(results)
    logging.info(f'No images scraped for city_id: {CITY_ID}')
