#!/usr/bin/env python3
# scrapes council member names and images.
import json
import logging
from datetime import datetime
# Use requests_html when JS is required on website
# https://requests.readthedocs.io/projects/requests-html/en/latest/
from requests_html import HTMLSession

session = HTMLSession()

# Change based off of which site being scraped
CITY_ID = 125
BASE_URL = 'https://www.cityofhenderson.com'
CITY_COUNCIL_URL = 'https://www.cityofhenderson.com/government/departments/mayor-and-council'
BASE_IMG_PATH = f'https://www.citystats.xyz/images/cities/{CITY_ID}'

PATH_ID = f'{CITY_ID}'

CURR_DATE = datetime.now().strftime('%d_%m_%Y')
LOG_FILENAME = f'log_{CURR_DATE}.txt'

log_format = '%(asctime)s - %(levelname)s - %(message)s'
logging.basicConfig(filename=LOG_FILENAME,
                    level=logging.INFO,
                    format=log_format)
console_handler = logging.StreamHandler()
console_handler.setFormatter(logging.Formatter(log_format))
logging.getLogger().addHandler(console_handler)


def parse_json(results):
    json_arr = []
    for result in results:
        data = {}
        data['city_id'] = CITY_ID
        # council_member usually needs to be changed
        data['council_member'] = result
        data['img_url'] = None
        json_arr.append(data)
    with open(f'./new_council_members/json/{PATH_ID}.json', 'w') as writeJSON:
        json.dump(json_arr, writeJSON, ensure_ascii=False)


def scrape_data():
    try:
        r = session.get(CITY_COUNCIL_URL)
        # r.html actually works, lsp doesn't like it for some reason...
        data = []
        results = r.html.find('li.sidenav_haschildren')
        for result in results:
            res = result.find('a')
            for r in res:
                if 'Mayor' in r.text or 'Ward' in r.text:
                    data.append(r.text)
        del data[0]
        for i, d in enumerate(data):
            if 'Mayor' in d:
                data[i] = d.split('Mayor ')[1]
            elif 'Ward' in d:
                data[i] = d.split('- ')[1]
        return data
    except Exception as e:
        logging.error(f'Error at city_id: {CITY_ID} during scraping: {str(e)}')
        return False


if __name__ == "__main__":
    results = scrape_data()
    if results:
        parse_json(results)
    logging.info(f'No images scraped for city_id: {CITY_ID}')
