#!/usr/bin/env python3
# scrapes council member names and images.
import json
import logging
from datetime import datetime
# Use requests_html when JS is required on website
# https://requests.readthedocs.io/projects/requests-html/en/latest/
from requests_html import HTMLSession

session = HTMLSession()

# Change based off of which site being scraped
CITY_ID = 167
BASE_URL = 'https://lacity.gov'
CITY_COUNCIL_URL = 'https://lacity.gov/directory#elected-officials'
MAYOR_URL = 'https://en.wikipedia.org/wiki/Los_Angeles'
MAYOR_IMG_URL = 'https://mayor.lacity.gov/'
BASE_IMG_PATH = f'https://www.citystats.xyz/images/cities/{CITY_ID}'

PATH_ID = f'{CITY_ID}'

CURR_DATE = datetime.now().strftime('%d_%m_%Y')
LOG_FILENAME = f'log_{CURR_DATE}.txt'

log_format = '%(asctime)s - %(levelname)s - %(message)s'
logging.basicConfig(filename=LOG_FILENAME,
                    level=logging.INFO,
                    format=log_format)
console_handler = logging.StreamHandler()
console_handler.setFormatter(logging.Formatter(log_format))
logging.getLogger().addHandler(console_handler)


def parse_json(results):
    json_arr = []
    for result in results:
        data = {}
        data['city_id'] = CITY_ID
        # council_member usually needs to be changed
        data['council_member'] = result
        json_arr.append(data)
    for i, data in enumerate(json_arr):
        if i == 0:
            data['img_url'] = f'{BASE_IMG_PATH}/mayor'
        else:
            data['img_url'] = f'{BASE_IMG_PATH}/city_council/{i}'
    with open(f'./new_council_members/json/{PATH_ID}.json', 'w') as writeJSON:
        json.dump(json_arr, writeJSON, ensure_ascii=False)


def scrape_data():
    try:
        r = session.get(CITY_COUNCIL_URL)
        # r.html actually works, lsp doesn't like it for some reason...
        data = []
        results = r.html.find('.views-field-title')
        for result in results:
            a_tags = result.find('a')
            for a_tag in a_tags:
                if 'href' in a_tag.attrs:
                    if 'mayor' in a_tag.text.lower(
                    ) or 'councilmember' in a_tag.text.lower():
                        data.append(a_tag.text.split('- ')[1])
        return data
    except Exception as e:
        logging.error(f'Error at city_id: {CITY_ID} during scraping: {str(e)}')
        return False


if __name__ == "__main__":
    results = scrape_data()
    if results:
        parse_json(results)
    logging.info(f'No images scraped for city_id: {CITY_ID}')
