#!/usr/bin/env python3
# scrapes council member names and images.
import json
import logging
from datetime import datetime
# Use requests_html when JS is required on website
# https://requests.readthedocs.io/projects/requests-html/en/latest/
from requests_html import HTMLSession

session = HTMLSession()

# Change based off of which site being scraped
CITY_ID = 309
BASE_URL = 'https://www.ci.vallejo.ca.us'
CITY_COUNCIL_URL = 'https://www.ci.vallejo.ca.us/cms/One.aspx?portalId=16925451&pageId=17554178'
BASE_IMG_PATH = f'https://www.citystats.xyz/images/cities/{CITY_ID}'

PATH_ID = f'{CITY_ID}'
IMG_PATH = f'./new_council_members/img/{PATH_ID}/'

CURR_DATE = datetime.now().strftime('%d_%m_%Y')
LOG_FILENAME = f'log_{CURR_DATE}.txt'

log_format = '%(asctime)s - %(levelname)s - %(message)s'
logging.basicConfig(filename=LOG_FILENAME,
                    level=logging.INFO,
                    format=log_format)
console_handler = logging.StreamHandler()
console_handler.setFormatter(logging.Formatter(log_format))
logging.getLogger().addHandler(console_handler)


def parse_json(results):
    json_arr = []
    for result in results:
        data = {}
        data['city_id'] = CITY_ID
        # council_member usually needs to be changed
        data['council_member'] = result
        data['img_url'] = None
        json_arr.append(data)
    with open(f'./new_council_members/json/{PATH_ID}.json', 'w') as writeJSON:
        json.dump(json_arr, writeJSON, ensure_ascii=False)


def scrape_data():
    try:
        r = session.get(CITY_COUNCIL_URL)
        # r.html actually works, lsp doesn't like it for some reason...
        data = []
        rough_data = []
        results = r.html.find('.advanced-data-display')
        for result in results:
            if len(result.text):
                if 'MAYOR' in result.text:
                    rough_data = result.text.split('\n')
        for rd in rough_data:
            if 'MAYOR' in rd or 'COUNCIL MEMBER' in rd:
                if rd not in data:
                    data.append(rd)
        for i, d in enumerate(data):
            if ', EDD' in d:
                del data[i]
        for i, d in enumerate(data):
            if 'MAYOR' in d:
                data[i] = d.split('MAYOR ')[1]
            elif 'COUNCIL MEMBER' in d:
                data[i] = d.split('COUNCIL MEMBER ')[1]
        for i, d in enumerate(data):
            data[i] = d.lower().title()
        return data
    except Exception as e:
        logging.error(f'Error at city_id: {CITY_ID} during scraping: {str(e)}')
        return False


if __name__ == "__main__":
    results = scrape_data()
    if results:
        parse_json(results)
    logging.info(f'No images scraped for city_id: {CITY_ID}')
