#!/usr/bin/env python3
# scrapes council member names and images.
import logging
from datetime import datetime
# Use requests_html when JS is required on website
# https://requests.readthedocs.io/projects/requests-html/en/latest/
#  from requests_html import HTMLSession

#  session = HTMLSession()

# Change based off of which site being scraped
CITY_ID = 313
BASE_URL = 'https://www.vbgov.com/'
CITY_COUNCIL_URL = 'https://s3.us-east-1.amazonaws.com/virginia-beach-departments-docs/voter/Forms-and-Documents/Guide-to-Elected-Officials.pdf'

CURR_DATE = datetime.now().strftime('%d_%m_%Y')
LOG_FILENAME = f'log_{CURR_DATE}.txt'

log_format = '%(asctime)s - %(levelname)s - %(message)s'
logging.basicConfig(filename=LOG_FILENAME,
                    level=logging.INFO,
                    format=log_format)
console_handler = logging.StreamHandler()
console_handler.setFormatter(logging.Formatter(log_format))
logging.getLogger().addHandler(console_handler)

if __name__ == "__main__":
    logging.warning(f'Site for city_id: {CITY_ID}, not scrapable.')
