const stateUrlParserOpts = {
    singleStateUrl: {
        string: import.meta.env.VITE_SINGLE_STATE_URL,
        regex: new RegExp(import.meta.env.VITE_SINGLE_STATE_REGEX),
        canDelUpTo: 29,
        minLength: 24,
    },
    singleStateWithSingleFieldUrl: {
        string: import.meta.env.VITE_SINGLE_STATE_FIELD,
        regex: new RegExp(import.meta.env.VITE_SINGLE_STATE_FIELD_REGEX),
        canDelUpTo: 29,
        minLength: 34,
    },
    singleStateWithSubFieldUrl: {
        string: import.meta.env.VITE_SINGLE_STATE_SUBFIELD,
        regex: new RegExp(import.meta.env.VITE_SINGLE_STATE_SUBFIELD_REGEX),
        canDelUpTo: 42,
        minLength: 46,
    },
    singleStateWithQueryUrl: {
        string: import.meta.env.VITE_SINGLE_STATE_QUERY,
        regex: new RegExp(import.meta.env.VITE_SINGLE_STATE_QUERY_REGEX),
        canDelUpTo: 58,
        minLength: 59,
    },
    stateFields: [
        'state_name',
        'state_abbreviation',
        'date_admitted',
        'capital',
        'largest_city',
        'elevation',
        'time_zone',
        'latitude',
        'longitude',
        'url',
        'flag_url',
        'insignia_url',
        'area',
        'population',
        'government',
    ],
    stateSubFields: ['governor', 'senators', 'house_delegates'],
}

const cityUrlParserOpts = {
    singleCityUrl: {
        string: 'https://citystats.xyz/cities/1',
        regex: /^https:\/\/citystats\.xyz\/cities\/(?:\d{1,3}|[\w]+)$/,
        canDelUpTo: 29,
        minLength: 24,
    },
    singleCityWithSingleFieldUrl: {
        string: 'https://citystats.xyz/cities/1/government',
        regex: /^https:\/\/citystats\.xyz\/cities\/(?:\d{1,3}|[\w]+)\/[\w]+$/,
        canDelUpTo: 29,
        minLength: 34,
    },
    singleCityWithSubFieldUrl: {
        string: 'https://citystats.xyz/cities/1/government/city_council',
        regex: /^https:\/\/citystats\.xyz\/cities\/(?:\d{1,3}|[\w]+)\/[\w]+\/[\w]+$/,
        canDelUpTo: 42,
        minLength: 46,
    },
    singleCityWithQueryUrl: {
        string: 'https://citystats.xyz/cities/202/government/city_council/50',
        regex: /^https:\/\/citystats\.xyz\/cities\/(?:\d{1,3}|[\w]+)\/[\w]+\/[\w]+\/\d{1,2}$/,
        canDelUpTo: 57,
        minLength: 58,
    },
    cityFields: [
        'city_name',
        'state_name',
        'coordinates',
        'settled_founded',
        'incorporated',
        'elevation',
        'time_zone',
        'fips_code',
        'url',
        'counties',
        'government',
        'area',
        'population',
        'zip_codes',
        'area_codes',
        'gnis_feature_ids',
    ],
    citySubFields: ['type', 'mayor', 'city_council'],
}

export { stateUrlParserOpts, cityUrlParserOpts }
